
# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg

locale: 'pt-br'

media_folder: "static/assets"
public_folder: "/assets"

publish_mode: editorial_workflow
backend:
  name: test-repo

local_backend: true

collections:
  - name: "desafios"
    label: "Desafios"
    folder: '_blog'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - {label: "Featured Image", name: "thumbnail",required: false, widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Save as Draft", name: “draft”, required: true, widget: "boolean", default: true}
      - { name: body, label: Body, widget: markdown }