import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { Heart, Path } from 'phosphor-react'
import Weare from '../src/components/Weare'
import Vagas from '../src/components/Vagas'

export default function Home() {
  const router = useRouter();

  const shortcutLists = [
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
    {
      title: 'Frontend',
      url: 'frontend/index.html',
    },
  ]

  return (
    <div className="py-0 px-8 text-white">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <div className=''>
        <video autoplay muted loop className="fixed min-h-full min-2-full right-0 bottom-0 top-0">
          <source src="/purplesound.mp4" type="video/mp4" />
        </video>

      </div> */}
      <main className={styles.main}>
        <div className="max-w-[1344px] mx-auto flex flex-col items-center my-20 w-[98%]">
        <img src="" alt="Logo" />
        <div className='items-center justify-center mx-auto flex flex-col'>
          <h2 className="text-6xl text-white font-black mt-20 block">
            <span className="text-transparent bg-gradient bg-clip-text">Sua trilha começa aqui.</span> 
          </h2>
          <span className='text-zinc-400 block mt-6'>
            Você faz o seu caminho. Nós criamos as trilhas.
          </span>
        </div>

        <div className="grid grid-cols-6 gap-8 mt-16 grid-flow-row">
            { shortcutLists.map( (item, id) =>{
              return(
                <>    
                  <a href={item.url} key={id} className="w-fit relative rounded-lg overflow-hidden">
                    {/* <img src="" alt="game " /> */}

                    <div className="py-3 px-4 bg-gradient-to-r from-primary to-[#fc5c7d] text-white rounded flex items-center gap-3 transition duration-500 ease-in-out">
                        {/* classname="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500" */}
                      <strong className="font-bold text-white block" >{item.title}</strong>
                      {/* <span className="text-zinc-300 text-sm block mt-1">
                        
                      </span> */}
                    </div>
                  </a>
                </>
              );
            } ) }
            
        </div>

        <div className="pt-1 bg-gradient self-stretch rounded-lg mt-8 overflow-hidden">
          <div className="bg-[#2A2634] px-8 py-6 flex justify-between items-center">
            <div>
              <strong className="text-2xl text-white font-black block" > Não encontrou sua trilha?</strong>
              <span className="text-zinc-400 block" >
                Comece a criar seu caminho!
              </span>
            </div>
        
            <button className="py-3 px-4 bg-primary text-white rounded hover:bg-[#3f51d6] flex items-center gap-3 transition duration-300 ease-in-out"
              onClick={() => {
                router.push('/signup');
              }}
            >
              <Path size={24} />
              Iniciar
            </button>

          </div>

        </div>

        </div>
      </main>

      <div className="min-h-screen" >
          <Weare />
      </div>

      {/* <Vagas /> */}

      <footer className={styles.footer}>
        <a
          href="/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with <Heart /> by{'SteamGroups '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
